server:
  port: 9898

spring:
  application:
    name: /

  # Liquibase
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  # datasource
  datasource:
    url: jdbc:mysql://172.26.3.254:3306/kafka_config?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: xxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      auto-commit: true
      minimum-idle: 3
kafka:
  # Kafka集群的地址
  bootstrap-servers: 172.26.1.151:9092
  consumer:
    enable-auto-commit: true
    group-id: kafka-group-one #群组ID
    auto-offset-reset: latest
    auto-commit-interval: 12000 #提交offset延时
    max-poll-records: 10 #单次拉取消息的最大条数
    consumer-client-id: kafka-client_${random.uuid}
    bean-method: com.mac.kafka.consumer.ConsumerRecive#consumeMessage01(java.util.List)
    enabled: true
    topics-listen:
      - send-kafka-custom
    properties:
      listener:
        concurrency: 100
      max:
        poll:
          interval:
            ms: 60000000
      session:
        timeout:
          ms: 120000 # 消费会话超时时间（超过这个时间 consumer 没有发送心跳，就会触发 rebalance 操作）
        request:
          timeout:
            ms: 18000 # 消费请求的超时时间
  listener:
    missing-topics-fatal: false # consumer listener topics 不存在时，启动项目就会报错
    poll-timeout: 60

# springdoc-openapi 项目配置
#springdoc:
#  # 任何方法中用作请求参数的 POJO（Plain Old Java Objects，简单老式Java对象）都将会被扁平化
#  default-flat-param-object: true
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: order
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: com.stackstone.example
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
#    enable-footer-custom: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.mac.kafka.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    pageable: false
  global-config:
    banner: false


